# Generated by Django 5.1.7 on 2025-03-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', '电子产品'), ('Clothing', '服装'), ('Home', '家居用品'), ('Books', '图书'), ('Sports', '体育用品'), ('Collectibles', '收藏品'), ('Toys', '玩具'), ('Beauty', '美妆护肤'), ('Automotive', '汽车用品'), ('Other', '其他')], default='Other', max_length=100),
        ),
    ]
