# Generated by Django 5.1.7 on 2025-03-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("sold", "Sold"), ("hidden", "Hidden")],
                default="active",
                max_length=10,
            ),
        ),
    ]
