# Generated by Django 5.1.7 on 2025-03-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("buyer", "Buyer"),
                    ("seller", "Seller"),
                    ("both", "Buyer & Seller"),
                    ("admin", "Admin"),
                ],
                default="both",
                max_length=10,
            ),
        ),
    ]
