# Generated by Django 5.1.7 on 2025-03-14 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_payment_status_alter_order_status'),
        ('reviews', '0004_review_updated_at_sellerreview_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sellerreview',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sellerreview',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_reviews', to='orders.order'),
        ),
    ]
