# Generated by Django 5.1.7 on 2025-03-14 01:16
from django.db import migrations
from django.utils import timezone

def set_updated_at_defaults(apps, schema_editor):
    SellerReview = apps.get_model('reviews', 'SellerReview')
    for review in SellerReview.objects.all():
        if not review.updated_at:
            review.updated_at = review.created_at or timezone.now()
            review.save()

class Migration(migrations.Migration):
    dependencies = [
        ('reviews', '0004_review_updated_at_sellerreview_updated_at_and_more'),
    ]

    operations = [
        migrations.RunPython(set_updated_at_defaults),
    ]
