# Generated by Django 5.1.7 on 2025-03-14 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_review_updated_at_alter_review_comment_and_more'),
        ('reviews', '0006_auto_20250314_0116'),
    ]

    operations = [
    ]
