# Generated by Django 4.2.16 on 2025-03-17 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_payment_status_alter_order_status"),
        ("reviews", "0007_merge_20250314_0118"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellerreview",
            name="comment",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="sellerreview",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="seller_reviews",
                to="orders.order",
            ),
        ),
    ]
